services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - skatedeck-network

networks:
  skatedeck-network:
    driver: bridge
