import { type Trick } from "@/app/page";

export const trickCards: Trick[] = [
  // Basic Ollies
  {
    id: 1,
    name: "Ollie",
    difficulty: "Beginner",
    points: 10,
    description: "The foundation of all skateboarding tricks",
  },
  {
    id: 2,
    name: "Nollie",
    difficulty: "Intermediate",
    points: 20,
    description: "Ollie off the nose",
  },
  {
    id: 3,
    name: "Fakie Ollie",
    difficulty: "Beginner",
    points: 12,
    description: "Ollie while riding fakie",
  },
  {
    id: 4,
    name: "Switch Ollie",
    difficulty: "Intermediate",
    points: 18,
    description: "Ollie in switch stance",
  },

  // Shove-Its
  {
    id: 5,
    name: "Frontside Pop Shove-It",
    difficulty: "Beginner",
    points: 15,
    description: "Board spins 180° frontside",
  },
  {
    id: 6,
    name: "Backside Pop Shove-It",
    difficulty: "Beginner",
    points: 15,
    description: "Board spins 180° backside",
  },
  {
    id: 7,
    name: "Nollie Shove-It",
    difficulty: "Intermediate",
    points: 22,
    description: "Shove-it from nollie position",
  },
  {
    id: 8,
    name: "Fakie Shove-It",
    difficulty: "Beginner",
    points: 16,
    description: "Shove-it while riding fakie",
  },
  {
    id: 9,
    name: "Switch Pop Shove-It",
    difficulty: "Intermediate",
    points: 20,
    description: "Shove-it in switch stance",
  },
  {
    id: 10,
    name: "Nollie Pop Shove-It",
    difficulty: "Intermediate",
    points: 24,
    description: "Pop shove-it from nollie",
  },
  {
    id: 11,
    name: "Fakie Pop Shove-It",
    difficulty: "Intermediate",
    points: 18,
    description: "Pop shove-it while riding fakie",
  },

  // 180s
  {
    id: 12,
    name: "Frontside 180",
    difficulty: "Intermediate",
    points: 20,
    description: "180° frontside turn",
  },
  {
    id: 13,
    name: "Backside 180",
    difficulty: "Intermediate",
    points: 20,
    description: "180° backside turn",
  },
  {
    id: 14,
    name: "Nollie Frontside 180",
    difficulty: "Advanced",
    points: 35,
    description: "Frontside 180 from nollie",
  },
  {
    id: 15,
    name: "Nollie Backside 180",
    difficulty: "Advanced",
    points: 35,
    description: "Backside 180 from nollie",
  },
  {
    id: 16,
    name: "Fakie Frontside 180",
    difficulty: "Intermediate",
    points: 22,
    description: "Frontside 180 from fakie",
  },
  {
    id: 17,
    name: "Fakie Backside 180",
    difficulty: "Intermediate",
    points: 22,
    description: "Backside 180 from fakie",
  },
  {
    id: 18,
    name: "Switch Frontside 180",
    difficulty: "Advanced",
    points: 30,
    description: "Frontside 180 in switch stance",
  },
  {
    id: 19,
    name: "Switch Backside 180",
    difficulty: "Advanced",
    points: 30,
    description: "Backside 180 in switch stance",
  },
  {
    id: 20,
    name: "Frontside Half-Cab",
    difficulty: "Intermediate",
    points: 25,
    description: "Fakie frontside 180",
  },
  {
    id: 21,
    name: "Backside Half-Cab",
    difficulty: "Intermediate",
    points: 25,
    description: "Fakie backside 180",
  },

  // Flip Tricks
  {
    id: 22,
    name: "Kickflip",
    difficulty: "Intermediate",
    points: 25,
    description: "Board flips along the length axis",
  },
  {
    id: 23,
    name: "Heelflip",
    difficulty: "Intermediate",
    points: 25,
    description: "Board flips opposite to kickflip",
  },
  {
    id: 24,
    name: "Frontside Kickflip",
    difficulty: "Advanced",
    points: 40,
    description: "Kickflip with frontside body rotation",
  },
  {
    id: 25,
    name: "Backside Kickflip",
    difficulty: "Advanced",
    points: 40,
    description: "Kickflip with backside body rotation",
  },
  {
    id: 26,
    name: "Nollie Kickflip",
    difficulty: "Advanced",
    points: 45,
    description: "Kickflip from nollie position",
  },
  {
    id: 27,
    name: "Fakie Kickflip",
    difficulty: "Advanced",
    points: 42,
    description: "Kickflip while riding fakie",
  },
  {
    id: 28,
    name: "Switch Kickflip",
    difficulty: "Advanced",
    points: 38,
    description: "Kickflip in switch stance",
  },
  {
    id: 29,
    name: "Nollie Heelflip",
    difficulty: "Advanced",
    points: 45,
    description: "Heelflip from nollie position",
  },
  {
    id: 30,
    name: "Fakie Heelflip",
    difficulty: "Advanced",
    points: 42,
    description: "Heelflip while riding fakie",
  },
  {
    id: 31,
    name: "Switch Heelflip",
    difficulty: "Advanced",
    points: 38,
    description: "Heelflip in switch stance",
  },
  {
    id: 32,
    name: "Varial Kickflip",
    difficulty: "Intermediate",
    points: 30,
    description: "Shove-it combined with kickflip",
  },
  {
    id: 33,
    name: "Varial Heelflip",
    difficulty: "Intermediate",
    points: 30,
    description: "Frontside shove-it with heelflip",
  },

  // Slides
  {
    id: 34,
    name: "Frontside Boardslide",
    difficulty: "Intermediate",
    points: 26,
    description: "Slide frontside on the middle of board",
  },
  {
    id: 35,
    name: "Backside Boardslide",
    difficulty: "Intermediate",
    points: 26,
    description: "Slide backside on the middle of board",
  },
  {
    id: 36,
    name: "Frontside Noseslide",
    difficulty: "Advanced",
    points: 35,
    description: "Slide on the nose frontside",
  },
  {
    id: 37,
    name: "Backside Noseslide",
    difficulty: "Advanced",
    points: 35,
    description: "Slide on the nose backside",
  },
  {
    id: 38,
    name: "Frontside Tailslide",
    difficulty: "Advanced",
    points: 35,
    description: "Slide on the tail frontside",
  },
  {
    id: 39,
    name: "Backside Tailslide",
    difficulty: "Advanced",
    points: 35,
    description: "Slide on the tail backside",
  },
  {
    id: 40,
    name: "Frontside Lipslide",
    difficulty: "Advanced",
    points: 38,
    description: "Lipslide approached frontside",
  },
  {
    id: 41,
    name: "Backside Lipslide",
    difficulty: "Advanced",
    points: 38,
    description: "Lipslide approached backside",
  },
  {
    id: 42,
    name: "Frontside Noseblunt Slide",
    difficulty: "Pro",
    points: 55,
    description: "Noseblunt slide frontside",
  },
  {
    id: 43,
    name: "Backside Noseblunt Slide",
    difficulty: "Pro",
    points: 55,
    description: "Noseblunt slide backside",
  },

  // Grinds
  {
    id: 44,
    name: "50-50 Grind",
    difficulty: "Intermediate",
    points: 22,
    description: "Grind on both trucks",
  },
  {
    id: 45,
    name: "Nosegrind",
    difficulty: "Intermediate",
    points: 24,
    description: "Grind on front truck only",
  },
  {
    id: 46,
    name: "5-0 Grind",
    difficulty: "Intermediate",
    points: 24,
    description: "Grind on back truck only",
  },
  {
    id: 47,
    name: "Frontside Feeble Grind",
    difficulty: "Advanced",
    points: 38,
    description: "Feeble grind approached frontside",
  },
  {
    id: 48,
    name: "Backside Feeble Grind",
    difficulty: "Advanced",
    points: 38,
    description: "Feeble grind approached backside",
  },
  {
    id: 49,
    name: "Frontside Smith Grind",
    difficulty: "Advanced",
    points: 38,
    description: "Smith grind approached frontside",
  },
  {
    id: 50,
    name: "Backside Smith Grind",
    difficulty: "Advanced",
    points: 38,
    description: "Smith grind approached backside",
  },
  {
    id: 51,
    name: "Crooked Grind",
    difficulty: "Advanced",
    points: 40,
    description: "Front truck over, back truck grinds",
  },
  {
    id: 52,
    name: "Frontside 5-0 Grind",
    difficulty: "Advanced",
    points: 32,
    description: "5-0 grind approached frontside",
  },
  {
    id: 53,
    name: "Backside 5-0 Grind",
    difficulty: "Advanced",
    points: 32,
    description: "5-0 grind approached backside",
  },
  {
    id: 54,
    name: "Frontside Crooked Grind",
    difficulty: "Advanced",
    points: 42,
    description: "Crooked grind approached frontside",
  },
  {
    id: 55,
    name: "Backside Crooked Grind",
    difficulty: "Advanced",
    points: 42,
    description: "Crooked grind approached backside",
  },
  {
    id: 56,
    name: "Salad Grind",
    difficulty: "Advanced",
    points: 45,
    description: "Crooked grind with tweaked style",
  },
  {
    id: 57,
    name: "Frontside Nosegrind",
    difficulty: "Advanced",
    points: 32,
    description: "Nosegrind approached frontside",
  },
  {
    id: 58,
    name: "Backside Nosegrind",
    difficulty: "Advanced",
    points: 32,
    description: "Nosegrind approached backside",
  },

  // Stalls
  {
    id: 59,
    name: "Axle Stall",
    difficulty: "Beginner",
    points: 15,
    description: "Stall on both trucks",
  },
  {
    id: 60,
    name: "Nose Stall",
    difficulty: "Beginner",
    points: 16,
    description: "Stall on the nose",
  },
  {
    id: 61,
    name: "Tail Stall",
    difficulty: "Beginner",
    points: 16,
    description: "Stall on the tail",
  },
  {
    id: 62,
    name: "Frontside Feeble Stall",
    difficulty: "Intermediate",
    points: 25,
    description: "Feeble stall approached frontside",
  },
  {
    id: 63,
    name: "Backside Feeble Stall",
    difficulty: "Intermediate",
    points: 25,
    description: "Feeble stall approached backside",
  },
  {
    id: 64,
    name: "Frontside Smith Stall",
    difficulty: "Intermediate",
    points: 25,
    description: "Smith stall approached frontside",
  },
  {
    id: 65,
    name: "Backside Smith Stall",
    difficulty: "Intermediate",
    points: 25,
    description: "Smith stall approached backside",
  },
  {
    id: 66,
    name: "Frontside Nose Stall",
    difficulty: "Intermediate",
    points: 22,
    description: "Nose stall approached frontside",
  },
  {
    id: 67,
    name: "Backside Nose Stall",
    difficulty: "Intermediate",
    points: 22,
    description: "Nose stall approached backside",
  },
  {
    id: 68,
    name: "Disaster",
    difficulty: "Intermediate",
    points: 28,
    description: "Backside axle stall",
  },
  {
    id: 69,
    name: "Backside Air Stall",
    difficulty: "Advanced",
    points: 35,
    description: "Stall while grabbing backside",
  },

  // Transition Tricks
  {
    id: 70,
    name: "Rock to Fakie",
    difficulty: "Beginner",
    points: 18,
    description: "Rock over coping and ride back fakie",
  },
  {
    id: 71,
    name: "Rock and Roll",
    difficulty: "Intermediate",
    points: 24,
    description: "Rock over and kick turn back in",
  },
  {
    id: 72,
    name: "Frontside Rock and Roll",
    difficulty: "Intermediate",
    points: 26,
    description: "Rock and roll approached frontside",
  },
  {
    id: 73,
    name: "Drop-In",
    difficulty: "Beginner",
    points: 12,
    description: "Drop into a ramp or bowl",
  },
  {
    id: 74,
    name: "Frontside Air",
    difficulty: "Advanced",
    points: 45,
    description: "Air with frontside grab",
  },
  {
    id: 75,
    name: "Backside Air",
    difficulty: "Advanced",
    points: 45,
    description: "Air with backside grab",
  },

  // Advanced Flip Tricks
  {
    id: 76,
    name: "360 Flip",
    difficulty: "Advanced",
    points: 50,
    description: "Combines kickflip and 360 shuvit",
  },
  {
    id: 77,
    name: "Hardflip",
    difficulty: "Advanced",
    points: 45,
    description: "Frontside shuvit with kickflip",
  },
  {
    id: 78,
    name: "Inward Heelflip",
    difficulty: "Advanced",
    points: 45,
    description: "Backside shuvit with heelflip",
  },
  {
    id: 79,
    name: "360 Shuvit",
    difficulty: "Intermediate",
    points: 28,
    description: "Board spins 360° horizontally",
  },
  {
    id: 80,
    name: "Frontside 360 Shuvit",
    difficulty: "Intermediate",
    points: 30,
    description: "Board spins 360° frontside",
  },
  {
    id: 81,
    name: "Backside 360 Shuvit",
    difficulty: "Intermediate",
    points: 30,
    description: "Board spins 360° backside",
  },

  // Manual Tricks
  {
    id: 82,
    name: "Manual",
    difficulty: "Beginner",
    points: 12,
    description: "Balance on back wheels",
  },
  {
    id: 83,
    name: "Nose Manual",
    difficulty: "Beginner",
    points: 12,
    description: "Balance on front wheels",
  },
  {
    id: 84,
    name: "Manual to Ollie",
    difficulty: "Intermediate",
    points: 25,
    description: "Manual to Ollie",
  },
  {
    id: 84,
    name: "Manual to Roll-in",
    difficulty: "Intermediate",
    points: 25,
    description: "Manual to Roll-in",
  },

  // Pro Level Tricks
  {
    id: 87,
    name: "Double Kickflip",
    difficulty: "Pro",
    points: 65,
    description: "Kickflip that rotates twice",
  },
  {
    id: 88,
    name: "Double Heelflip",
    difficulty: "Pro",
    points: 65,
    description: "Heelflip that rotates twice",
  },
  {
    id: 89,
    name: "Nollie 360 Flip",
    difficulty: "Pro",
    points: 75,
    description: "360 flip from nollie position",
  },
  {
    id: 91,
    name: "Fakie 360 Flip",
    difficulty: "Pro",
    points: 75,
    description: "360 flip while riding fakie",
  },
  {
    id: 92,
    name: "Kickflip 360",
    difficulty: "Pro",
    points: 68,
    description: "Kickflip with full body rotation",
  },

  {
    id: 94,
    name: "Frontside 360",
    difficulty: "Advanced",
    points: 40,
    description: "Full frontside rotation",
  },
  {
    id: 95,
    name: "Backside 360",
    difficulty: "Advanced",
    points: 40,
    description: "Full backside rotation",
  },
];
